const content =
    {
      "header": "Joey Maximum",
      "copy": [
        "JOEY MAXIMUM IS THE MOST JOEY YOU WILL EVER SEE IN YOUR WHOLE LIFE! HE IS AN UPSTOPPABLE TORNADO OF UNBRIDLED FURY WHO WILL COME DOWN ON YOU WITH THE FORCE OF A THOUSAND THUNDEROUS HAMMERS!",
        "WHEN JOEY MAXIMUM (JUST \"MAXIMUM\" TO HIS FRIENDS) COMES TO THE TABLE FOOTBALL TABLE, YOU'RE IN FOR A WORLD OF PAIN! SO BUCKLE UP YOU POOR FOOLS, AND PRAY TO ANY GOD YOU CARE TO, CAUSE THE JOEY MAXIMUM TRAIN IS ROLLING THROUGH TOWN AND YOU BETTER GET OUT OF THE WAY!!"
      ]
    }

export default content
